export const CATEGORIES = [
  { name: 'Snacks', emoji: '🍿', type: 'expense', defaultLimit: 2000 },
  { name: 'Food', emoji: '🍽️', type: 'expense', defaultLimit: 5000 },
  { name: 'Academics', emoji: '📚', type: 'expense', defaultLimit: 1000 },
  { name: 'Beauty', emoji: '💄', type: 'expense', defaultLimit: 1000 },
  { name: 'Household', emoji: '🏠', type: 'expense', defaultLimit: 2000 },
  { name: 'Transport', emoji: '🚌', type: 'expense', defaultLimit: 1500 },
  { name: 'Entertainment', emoji: '🎬', type: 'expense', defaultLimit: 2000 },
  { name: 'Health', emoji: '💊', type: 'expense', defaultLimit: 1000 },
  { name: 'Pocket Money', emoji: '👝', type: 'income' },
  { name: 'Salary', emoji: '💼', type: 'income' },
  { name: 'Freelance', emoji: '💻', type: 'income' },
  { name: 'Side Income', emoji: '🛒', type: 'income' },
  { name: 'Scholarship', emoji: '🎓', type: 'income' },
  { name: 'Part-time Job', emoji: '🕐', type: 'income' },
  { name: 'Investment', emoji: '📈', type: 'income' },
  { name: 'Gift', emoji: '🎁', type: 'income' },
  { name: 'Selling', emoji: '🏷️', type: 'income' },
  { name: 'Family Transfer', emoji: '🏠', type: 'income' },
  { name: 'Wallet Top-Up', emoji: '💳', type: 'income' },
  { name: 'Savings Top-Up', emoji: '🏦', type: 'income' },
];
